-- AlterTable
ALTER TABLE "Check" ALTER COLUMN "date" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "time1" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "time2" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "time3" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "time4" SET DEFAULT CURRENT_TIMESTAMP;
